#encoding: utf-8

node = Node.create(:name => "房产信息")
Category.create(:node_id => node.id, :name => "出租房")
Category.create(:node_id => node.id, :name => "求租房")
Category.create(:node_id => node.id, :name => "商铺出租")
Category.create(:node_id => node.id, :name => "商铺求租")
Category.create(:node_id => node.id, :name => "二手房出售")
Category.create(:node_id => node.id, :name => "二手房求购")

node = Node.create(:name => "物品交易")
Category.create(:node_id => node.id, :name => "二手电脑")
Category.create(:node_id => node.id, :name => "二手笔记本")
Category.create(:node_id => node.id, :name => "手机/通讯相关")
Category.create(:node_id => node.id, :name => "音响/乐器/影音")
Category.create(:node_id => node.id, :name => "艺术/工艺/收藏品")

node = Node.create(:name => "生活服务")
Category.create(:node_id => node.id, :name => "招聘")
Category.create(:node_id => node.id, :name => "求职")
Category.create(:node_id => node.id, :name => "家政")
Category.create(:node_id => node.id, :name => "保洁")
Category.create(:node_id => node.id, :name => "搬家")
Category.create(:node_id => node.id, :name => "装修/装饰")
Category.create(:node_id => node.id, :name => "家电维修")
Category.create(:node_id => node.id, :name => "礼仪婚庆")
Category.create(:node_id => node.id, :name => "写真/婚纱摄影")
Category.create(:node_id => node.id, :name => "养生保健")
Category.create(:node_id => node.id, :name => "送水/送气")
Category.create(:node_id => node.id, :name => "订票/特价机票")

node = Node.create(:name => "商务信息")
Category.create(:node_id => node.id, :name => "快递")
Category.create(:node_id => node.id, :name => "喷绘招牌")
Category.create(:node_id => node.id, :name => "设计")
Category.create(:node_id => node.id, :name => "印刷")
Category.create(:node_id => node.id, :name => "网站建设")
Category.create(:node_id => node.id, :name => "招商加盟")
Category.create(:node_id => node.id, :name => "物流货运")
Category.create(:node_id => node.id, :name => "其他")

node = Node.create(:name => "交友信息")
Category.create(:node_id => node.id, :name => "找女友")
Category.create(:node_id => node.id, :name => "找男友")
Category.create(:node_id => node.id, :name => "女士征婚")
Category.create(:node_id => node.id, :name => "男士征婚")
Category.create(:node_id => node.id, :name => "兴趣交友")
Category.create(:node_id => node.id, :name => "技能交换")
Category.create(:node_id => node.id, :name => "寻人寻友")
Category.create(:node_id => node.id, :name => "其它")

node = Node.create(:name => "车辆买卖服务")
Category.create(:node_id => node.id, :name => "二手汽车买卖")
Category.create(:node_id => node.id, :name => "租车/代驾")
Category.create(:node_id => node.id, :name => "带车求职")
Category.create(:node_id => node.id, :name => "无车司机求职")
Category.create(:node_id => node.id, :name => "自行车/摩托车/助动车买卖")
Category.create(:node_id => node.id, :name => "汽修/保养")
Category.create(:node_id => node.id, :name => "车辆配件")
Category.create(:node_id => node.id, :name => "新车买卖")
Category.create(:node_id => node.id, :name => "驾校/陪练")

node = Node.create(:name => "教育培训")
Category.create(:node_id => node.id, :name => "家教")
Category.create(:node_id => node.id, :name => "外语培训")
Category.create(:node_id => node.id, :name => "文艺/体育")
Category.create(:node_id => node.id, :name => "中小学教育")
Category.create(:node_id => node.id, :name => "电脑/网络")

node = Node.create(:name => "餐饮娱乐")
Category.create(:node_id => node.id, :name => "家常菜")
Category.create(:node_id => node.id, :name => "咖啡厅")
Category.create(:node_id => node.id, :name => "酒吧")
Category.create(:node_id => node.id, :name => "KTV")
Category.create(:node_id => node.id, :name => "美容美发")
Category.create(:node_id => node.id, :name => "洗浴")
Category.create(:node_id => node.id, :name => "棋牌室")

NewsCategory.create(:name => "新闻")
NewsCategory.create(:name => "关于")

